### ISSUE TITLE
Token warning when used with Paragraphs

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/youtube#16]
Per https://github.com/backdrop-contrib/paragraphs/issues/16

Using a Youtube Field in a Paragraph bundle/type gives a warning in the status page:

![screen shot 2018-09-25 at 1 22 38 pm](https://user-images.githubusercontent.com/871421/46035196-1ac65d80-c0c8-11e8-9f6b-6916c18ea313.jpg)

> The following token types are not defined but have tokens:
> - $info['types']['paragraphs_item']

**Comment by laryn** [comment]
@jenlampton Does this seem reasonable?
https://github.com/laryn/youtube/commit/54d40e90329ebad95dd466fdacda563f86ec1b46

**Comment by jenlampton** [comment]
Is there anything else we can test for than the entity being a Paragraph? I'd love to make this a little more robust so that if there are any other entity types we don't end up with a huge long list. 

Edit: How do other field types do it? Do they have the token issue too? If not, why not?

**Comment by laryn** [comment]
@jenlampton Youtube field is the only one I've seen this happen with to date, but I'll try to do a little more testing from that angle. I'm also open to adding something to Paragraphs, obviously, just not sure what it would be yet.

**Comment by laryn** [comment]
@jenlampton I think this is better. 

https://github.com/laryn/youtube/pull/1/files

**Comment by jenlampton** [comment]
Yes, looks great! :)

edit: Hm...  looks like GitHub removed the ability to merge directly from the PR?!?

**Comment by jenlampton** [comment]
Oh, it looks like there aren't any PRs against this project, is that one against your fork maybe @laryn? Can you create a PR against YouTube (or maybe update that one?)

**Comment by laryn** [comment]
I think I did that a little strangely by forking, then PRing to my own fork instead of the main repo...

**Comment by laryn** [comment]
I squash-merged into my fork and then PRed here.

**Comment by jenlampton** [comment]
Fixed by https://github.com/backdrop-contrib/youtube/pull/17

**Comment by olafgrabienski** [comment]
Thanks for the fix! @jenlampton, are you planning to make a new release?
