### ISSUE TITLE
Cannot activate "YouTube Field Colorbox" submodule

### ISSUE THREAD

**Issue by sternhagel** [backdrop-contrib/youtube#20]
When trying to activate "YouTube Field Colorbox" submodule, the system shows the following error:

> ParseError: syntax error, unexpected '$domain' (T_VARIABLE) in backdrop_load() (line 165 in [...]/modules/youtube/modules/youtube_colorbox/youtube_colorbox.module).

**Comment by olafgrabienski** [comment]
This seems to be a duplicate of https://github.com/backdrop-contrib/youtube/issues/20.

@jenlampton Are you up to make a new release which contains the fix for #20?
