### ISSUE TITLE
YouTube privacy setting ignored in "YouTube Colorbox" submodule

### ISSUE THREAD

**Issue by sternhagel** [backdrop-contrib/youtube#21]
When using the "YouTube Colorbox" submodule, the setting "Enable privacy-enhanced mode" is being ignored. Videos are always embedded with the "youtube.com"-Domain.

I did a little debugging, and the problem seems to be line 164 in "youtube_colorbox.module":
`$config = config('youtube.settings');`
The config() function returns an empty object in this case - but I don't understand why.

My current workaround is this:
`$privacy = config_get('youtube.settings', 'youtube_privacy');
$domain = $privacy ? 'youtube-nocookie.com' : 'youtube.com';`
But that's not a real solution because there's more code in the following lines trying to use the "$config" object.

The question is, why does the config() function return an empty object?

**Comment by Graham-72** [comment]
This submodule was not using the prefix 'youtube_' for the names of youtube config settings. PR #22 should fix this.

**Comment by sternhagel** [comment]
@Graham-72 Thanks, this PR fixes the issue for me.

There's one more thing I just noticed - "youtube-nocookie.com" seems to work only with "www." prefix. I'm attaching a patch here.
[youtube_colorbox.www.patch.txt](https://github.com/backdrop-contrib/youtube/files/4185437/youtube_colorbox.www.patch.txt)

**Comment by jenlampton** [comment]
Thanks @sternhagel I've created another issue to address the other problem:
https://github.com/backdrop-contrib/youtube/issues/24
