### ISSUE TITLE
Deprecated drupal_html_class function

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/youtube#26]
In youtube.module Line 535 is a deprecated drupal function, namely `drupal_html_class`
https://github.com/backdrop-contrib/youtube/blob/045bfecd47b23eb4f507b031c96e438d080b84c7/youtube.module#L535

See [deprecation notice](https://docs.backdropcms.org/api/backdrop/core%21includes%21drupal.inc/function/drupal_html_class/1)

PR to follow

**Comment by jenlampton** [comment]
The fix in the PR looks great! I will merge it as soon as the fix for #28 has been removed :)
