### ISSUE TITLE
replace link to Drupal module (imagestyleflush) w link to Backdrop version

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/youtube#28]
youtube.inc contains reference to imagestyleflush which does not exist for backdrop

https://github.com/backdrop-contrib/youtube/blob/045bfecd47b23eb4f507b031c96e438d080b84c7/youtube.inc#L152-L154

https://github.com/backdrop-contrib/youtube/blob/045bfecd47b23eb4f507b031c96e438d080b84c7/youtube.inc#L159

![image](https://user-images.githubusercontent.com/20357797/159332049-79336ac9-6c73-4bfe-b36f-3bd8834be766.png)

This appears when you click this button:
![image](https://user-images.githubusercontent.com/20357797/159331937-b3873f94-0ab1-498c-9a03-6cc0abba252b.png)

Possibly, the best solution is just to remove this hint?  PR to follow

**Comment by jenlampton** [comment]
Because there is a Drupal 7 version of [imagestyleflush](https://www.drupal.org/project/imagestyleflush), I'd like to leave the link.  Once that project gets ported to backdrop we can update the link, but if we remove the text entirely people won't know that there is a module that can help with this problem. Knowing there's a Drupal module might still help someone who needs the feature.

**Comment by jenlampton** [comment]
For now, I've changed the title of this issue so it can serve as a placeholder for a future update. Another option could be to remove the link to drupal.org, but leave the text (and maybe also place the link to drupal.org into the readme?). My preference is to leave it as-is for now, but if you (or others) feel strongly about removing the link, there is this other option :)

**Comment by jenlampton** [comment]
Question from @yorkshire-pudding I'm moving over here:

> Would it make sense to change the message to say that the module hasn't yet been ported?

**Comment by jenlampton** [comment]
I don't think that's necessary if we leave the link to drupal.org. Plus, there could be a period of time when it's not true (if the module gets ported and we don't notice right away), or if we fix the link but don't issue a release immediately.

**Comment by yorkshire-pudding** [comment]
@jenlampton - I checked for this module and there is now a placeholder at https://github.com/backdrop-contrib/imagestyleflush that directs people to the Image Effects module. I see this is now within the [Image Styles Admin](https://github.com/backdrop-contrib/image_effects/tree/1.x-1.x/image_styles_admin) submodule of that module.

Suggested text:

> Derivatives generated with image styles were not deleted. The 'Image Styles Admin' submodule of the 'Image Effects' module may help with that.

With a link to https://backdropcms.org/project/image_effects
Happy to do a PR if you're happy with text.
