### ISSUE TITLE
Start time display on node edit form is wrong

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/youtube#47]
To reproduce:

1. Add a Youtube field to a node type
2. Create a node and enter the following link:
https://youtu.be/X8OoRygGQvI?si=M0HF4FqbIi7emyJQ&t=112

The above starts after 112 seconds (1 minute and 52 seconds)

3. Save
4. Edit the node:

<img width="613" alt="Screen Shot 2023-12-15 at 6 48 16 AM" src="https://github.com/backdrop-contrib/youtube/assets/9938978/2b032249-e638-4cc6-94bb-ea707f3bc0d6">

**Comment by yorkshire-pudding** [comment]
I can't reproduce, at least on my dev version which has the fix for #45 

Copying that URL I get:
![image](https://github.com/backdrop-contrib/youtube/assets/20357797/f88e254c-24bc-4a1b-a4d8-17a6de9ba219)

Could it be something to do with timezones? YES!

I've added fix in the PR for #45

**Comment by argiepiano** [comment]
Great, @yorkshire-pudding! However, see my comment there. Using `gmdate()` (or `date()`) has the limitation you can't convert a number bigger than 86400 (24 hours).  This is unlikely to be a problem with Youtube videos, though. There are alternative math/sprintf ways as outlined in the link in my comment there.
